name: pr-title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  pr-title:
    uses: melodic-software/ci-workflows/.github/workflows/semantic-pr.yml@e103a330577206213a4ebc0919029d2533c39cdb # e103a33 2026-07-10
